"""DateTime

Revision ID: 93c11d3794f2
Revises: dbeca7a391f5
Create Date: 2021-02-08 15:24:58.305549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93c11d3794f2'
down_revision = 'dbeca7a391f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'time_of_waiting')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('time_of_waiting', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
